server:
  port: 8700
spring:
  application:
    name: geteway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    consul:
      host: localhost
      port: 8500
      discovery:
        register-health-check: false
