server:
  port: 8801
spring:
  application:
    name: consul-customer1
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: consul-c1
        register-health-check: false
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1
feign:
  hystrix:
    enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
management:
  endpoints:
    web:
      exposure:
        include: "*"
