server:
  port: 8002
spring:
  application:
    name: consul-producer2
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: consul-producer
        register-health-check: false
